// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417072039_addedtaxmodel")]
    partial class addedtaxmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_EmpId")
                        .HasColumnType("int");

                    b.Property<int?>("Entity_Id")
                        .HasColumnType("int");

                    b.Property<string>("Entity_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("Employee_EmpId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BackEnd.Models.Award", b =>
                {
                    b.Property<int>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AwardId"));

                    b.Property<string>("Award_Type")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Employee_EmpId")
                        .HasColumnType("int");

                    b.Property<double>("Exercise_Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("Grant_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Total_Units")
                        .HasColumnType("int");

                    b.HasKey("AwardId");

                    b.HasIndex("Employee_EmpId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("BackEnd.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<DateTime>("EmpDOJ")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpEmail")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BackEnd.Models.ExerciseRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("Awards_AwardId")
                        .HasColumnType("int");

                    b.Property<int>("Employee_EmpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Requested_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Units_Requested")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("Awards_AwardId");

                    b.HasIndex("Employee_EmpId");

                    b.ToTable("ExerciseRequests");
                });

            modelBuilder.Entity("BackEnd.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_EmpId")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Read")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("NotificationId");

                    b.HasIndex("Employee_EmpId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BackEnd.Models.VestingSchedule", b =>
                {
                    b.Property<int>("Vesting_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vesting_Id"));

                    b.Property<int>("Awards_AwardId")
                        .HasColumnType("int");

                    b.Property<int>("Cumulative_Vested")
                        .HasColumnType("int");

                    b.Property<int>("Employee_EmpId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Units_Vested")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vesting_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Vesting_Id");

                    b.HasIndex("Awards_AwardId");

                    b.HasIndex("Employee_EmpId");

                    b.ToTable("VestingSchedules");
                });

            modelBuilder.Entity("BackEnd.Models.AuditLog", b =>
                {
                    b.HasOne("BackEnd.Models.Employee", "Employee")
                        .WithMany("AuditLogs")
                        .HasForeignKey("Employee_EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BackEnd.Models.Award", b =>
                {
                    b.HasOne("BackEnd.Models.Employee", "Employee")
                        .WithMany("Awards")
                        .HasForeignKey("Employee_EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BackEnd.Models.ExerciseRequest", b =>
                {
                    b.HasOne("BackEnd.Models.Award", "Award")
                        .WithMany("ExerciseRequests")
                        .HasForeignKey("Awards_AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Employee", "Employee")
                        .WithMany("ExerciseRequests")
                        .HasForeignKey("Employee_EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BackEnd.Models.Notification", b =>
                {
                    b.HasOne("BackEnd.Models.Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("Employee_EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BackEnd.Models.VestingSchedule", b =>
                {
                    b.HasOne("BackEnd.Models.Award", "Award")
                        .WithMany("VestingSchedules")
                        .HasForeignKey("Awards_AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Employee", "Employee")
                        .WithMany("VestingSchedules")
                        .HasForeignKey("Employee_EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BackEnd.Models.Award", b =>
                {
                    b.Navigation("ExerciseRequests");

                    b.Navigation("VestingSchedules");
                });

            modelBuilder.Entity("BackEnd.Models.Employee", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Awards");

                    b.Navigation("ExerciseRequests");

                    b.Navigation("Notifications");

                    b.Navigation("VestingSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
